image: docker:latest

download:
  image: node:8
  stage: build
  cache:
    key: data
    untracked: true
    paths:
    - data/
    - node_modules/
    - package-lock.json
  variables:
    ftp_proxy: $https_proxy
  script:
  - mkdir -p /opt
  - ln -s $(pwd)/data /opt/mlst
  - yarn
  only:
  - tags
