image: docker:latest

download_cgmlst:
  image: node:8
  stage: build
  cache:
    key: node
    untracked: true
    paths:
    - node_modules/
  variables:
    ftp_proxy: $https_proxy
    RUN_CORE_GENOME_MLST: "yes"
  script:
  - mkdir -p /opt
  - ln -s $(pwd)/data /opt/mlst
  - yarn install
  - if [[ -f /nfs/wgsa/gitlab-cache/cgps-mlst/latest.tgz ]]; then tar -xzvf /nfs/wgsa/gitlab-cache/cgps-mlst/latest.tgz; echo "[$(date)] Used cache"; else echo "[$(date)] No cache found"; fi
  - touch wait.lock
  - while [[ -f wait.lock ]]; do sleep 10; done
  - DEBUG="*,-follow-redirects" npm run download
  only:
  - tags
