image: docker:latest

download_cgmlst:
  image: node:8
  stage: build
  cache:
    key: data
    untracked: true
    paths:
    - data/
    - node_modules/
  variables:
    ftp_proxy: $https_proxy
    RUN_CORE_GENOME_MLST: "yes"
  script:
  - rm -r data/cache/www.cgmlst.org package-lock.json yarn.lock node_modules/*
