image: docker:latest

download:
  stage: build
  image: node:8
  cache:
    key: data
    untracked: true
    paths:
    - data/
    - node_modules/
  variables:
    DEBUG: '*,-follow-redirects'
    ftp_proxy: $https_proxy
  script:
  - echo "container:$(pwd)>"
  - ls
  - ln -s $(pwd)/data /opt/mlst
  - npm install
  - npm run download
  only:
  - tags

fresh_download:
  stage: build
  image: node:8
  cache:
    key: data
    untracked: true
    paths:
    - data/
    - node_modules/
  variables:
    DEBUG: '*,-follow-redirects'
    ftp_proxy: $https_proxy
  script:
  - echo "container:$(pwd)>"
  - ls
  - ln -s $(pwd)/data /opt/mlst
  - rm -r data/*
  - npm install
  - npm run download
  only:
  - schedules

deploy:
  stage: deploy
  cache:
    key: data
    untracked: true
    paths:
    - data/
  script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker build
    --pull
    --build-arg http_proxy=$http_proxy
    --build-arg https_proxy=$https_proxy
    --build-arg ftp_proxy=$https_proxy
    -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
  - tags
  - schedules
