image: docker:latest

download_cgmlst:
  image: node:8
  stage: build
  cache:
    key: data
    untracked: true
    paths:
    - data/
    - node_modules/
  variables:
    ftp_proxy: $https_proxy
    RUN_CORE_GENOME_MLST: "yes"
  script:
  - mkdir -p /opt
  - ln -s $(pwd)/data /opt/mlst
  - yarn install
  - touch wait.lock
  - while [[ -f wait.lock ]]; do sleep 10; done
