cache:
  paths:
    - cgps-typing-databases/
    - node_modules/

stages:
  - index
  - test
  - deploy

index all mlst schemes:
  stage: index
  image: node:10
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "no"
  artifacts:
    paths:
    - index_dir/
    expire_in: 2 days
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
    - ./bin/pull_database.sh cgps-typing-databases
    - yarn install
    - npm run index -- --type=mlst --index=index_dir --database=cgps-typing-databases

test all mlst schemes:
  stage: test
  image: docker:latest
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "no"
  script:
    - docker build
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --target test_build
      -t "$CI_REGISTRY_IMAGE:mlst-test" .
    - tar c . | docker run -i --rm
      -v /usr/local/mlst/node_modules
      -v $(pwd):/usr/local/mlst
      -w /usr/local/mlst
      -e CI=true
      -e DEBUG='cgps:*,-cgps:trace*'
      $CI_REGISTRY_IMAGE:mlst-test
        bash -c "tar x && npm run test"

deploy all mlst schemes:
  stage: deploy
  image: docker:latest
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "no"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - DATABASE_UPDATED=$(cat index_dir/updated.txt)
    - if [[ -z "${CI_COMMIT_TAG:-}" ]]; then TAG="${DATABASE_UPDATED}-${CI_COMMIT_SHA::8}"; else TAG="${DATABASE_UPDATED}-${CI_COMMIT_TAG}"; fi
    - docker build
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --label "git-ref=${CI_COMMIT_REF_NAME},git-commit=${CI_COMMIT_SHA},gitlab-job-id=${CI_JOB_ID},database-updated=${DATABASE_UPDATED}"
      --target prod_build
      -t "$CI_REGISTRY_IMAGE:mlst-$TAG" .
    - docker push "$CI_REGISTRY_IMAGE:mlst-$TAG"

index all cgmlst schemes:
  stage: index
  image: node:10
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "yes"
  except:
    variables:
      - $SCHEME
  artifacts:
    paths:
    - index_dir/
    expire_in: 2 days
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
    - ./bin/pull_database.sh cgps-typing-databases
    - yarn install
    - npm run index -- --type=cgmlst --max-sequences 50 --index=index_dir --database=cgps-typing-databases

test all cgmlst schemes:
  stage: test
  image: docker:latest
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "yes"
  except:
    variables:
      - $SCHEME
  script:
    - docker build
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --target test_build
      -t "$CI_REGISTRY_IMAGE:mlst-test" .
    - tar c . | docker run -i --rm
      -v /usr/local/mlst/node_modules
      -v $(pwd):/usr/local/mlst
      -w /usr/local/mlst
      -e CI=true
      -e DEBUG='cgps:*,-cgps:trace*'
      -e RUN_CORE_GENOME_MLST=yes
      $CI_REGISTRY_IMAGE:mlst-test
        bash -c "tar x && npm run test"

quick test of staph cgmlst:
  stage: test
  image: docker:latest
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "yes"
  except:
    variables:
      - $SCHEME
  script:
    - docker build
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --target test_build
      -t "$CI_REGISTRY_IMAGE:mlst-test" .
    - tar c . | docker run -i --rm
      -v /usr/local/mlst/node_modules
      -v $(pwd):/usr/local/mlst
      -w /usr/local/mlst
      -e CI=true
      -e DEBUG='cgps:*,-cgps:trace*'
      -e RUN_CORE_GENOME_MLST=yes
      $CI_REGISTRY_IMAGE:mlst-test
        bash -c "tar x && node --max_old_space_size=4096 ./node_modules/.bin/ava --serial tests/quickCgMlst.js"

deploy all cgmlst schemes:
  stage: deploy
  image: docker:latest
  only:
    variables:
      - $RUN_CORE_GENOME_MLST == "yes"
  except:
    variables:
      - $SCHEME
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - DATABASE_UPDATED=$(cat index_dir/updated.txt)
    - if [[ -z "${CI_COMMIT_TAG:-}" ]]; then TAG="${DATABASE_UPDATED}-${CI_COMMIT_SHA::8}"; else TAG="${DATABASE_UPDATED}-${CI_COMMIT_TAG}"; fi
    - docker build
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg RUN_CORE_GENOME_MLST=yes
      --label "git-ref=${CI_COMMIT_REF_NAME},git-commit=${CI_COMMIT_SHA},gitlab-job-id=${CI_JOB_ID},database-updated=${DATABASE_UPDATED}"
      --target prod_build
      -t "$CI_REGISTRY_IMAGE:cgmlst-$TAG" .
    - docker push "$CI_REGISTRY_IMAGE:cgmlst-$TAG"

index some schemes:
  stage: index
  image: node:10
  only:
    variables:
      - $INDEX_PARAMS
  artifacts:
    paths:
    - index_dir/
    expire_in: 2 days
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
    - ./bin/pull_database.sh cgps-typing-databases
    - yarn install
    - npm run index -- $INDEX_PARAMS --index=index_dir --database=cgps-typing-databases

deploy some schemes:
  stage: deploy
  image: docker:latest
  only:
    variables:
      - $SCHEME_NAME
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - DATABASE_UPDATED=$(cat index_dir/updated.txt)
    - if [[ -z "${CI_COMMIT_TAG:-}" ]]; then TAG="${DATABASE_UPDATED}-${CI_COMMIT_SHA::8}"; else TAG="${DATABASE_UPDATED}-${CI_COMMIT_TAG}"; fi
    - docker build
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      $BUILD_PARAMS
      --label "git-ref=${CI_COMMIT_REF_NAME},git-commit=${CI_COMMIT_SHA},gitlab-job-id=${CI_JOB_ID},database-updated=${DATABASE_UPDATED}"
      -t "$CI_REGISTRY_IMAGE:${SCHEME_NAME}-$TAG" .
      --target prod_build
    - docker push "$CI_REGISTRY_IMAGE:${SCHEME_NAME}-$TAG"
