FROM    ubuntu:24.04 AS blast_build

RUN     apt-get update && apt-get install -y wget tar && \
        rm -rf /var/lib/apt/lists/* && \
        wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-x64-linux.tar.gz && \
        tar xzvf ncbi-blast-*-x64-linux.tar.gz && \
        mv ncbi-blast-*/bin /blast

FROM    node:22-slim AS base_build

WORKDIR /usr/local/mlst
COPY    --from=blast_build /blast/blastn /blast/makeblastdb /usr/local/bin/

RUN     apt-get update && apt-get install -y \
        git \
        python3 \
        python3-pip \
        build-essential \
        && rm -rf /var/lib/apt/lists/*

COPY    package.json /usr/local/mlst/
RUN     npm install --omit=dev --force

FROM    node:22-slim AS prod_build

COPY    --from=base_build /usr/local/mlst/node_modules /usr/local/mlst/node_modules
COPY    --from=blast_build /blast/blastn /blast/makeblastdb /usr/local/bin/
COPY    *.js package.json package-lock.json /usr/local/mlst/
COPY    src /usr/local/mlst/src/

WORKDIR /usr/local/mlst

ENTRYPOINT [ "/usr/local/bin/node", "/usr/local/mlst/index.js" ]