FROM ubuntu as blast_build

RUN apt-get update && apt-get install -y wget tar
RUN wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.7.1+-x64-linux.tar.gz
RUN tar xzvf ncbi-blast-2.7.1+-x64-linux.tar.gz
RUN cp ncbi-blast-2.7.1+/bin/blastn /

FROM node:8 as index_build

COPY    data/cache /opt/mlst/cache
RUN     mkdir -p /usr/local/mlst /opt/mlst/databases && \
        chmod -R a+w /opt/mlst/databases
WORKDIR /usr/local/mlst
COPY    index.js update-mlst-databases.js update-cgMLST-databases.js package.json /usr/local/mlst/
COPY    download_src /usr/local/mlst/download_src/
COPY    src /usr/local/mlst/src/
RUN     npm install
RUN     DEBUG='*,-follow-redirects' node ./update-mlst-databases.js && \
        chmod -R a+r /opt/mlst/databases 

FROM node:8

COPY    --from=blast_build /blastn /usr/local/bin
COPY    --from=index_build /opt/mlst/databases /opt/mlst/databases
COPY    --from=index_build /usr/local/mlst /usr/local/mlst/
WORKDIR /usr/local/mlst

CMD [ "/usr/local/bin/node", "--max-old-space-size=4096", "/usr/local/mlst/index.js" ]
