FROM biocontainers/blast

USER root
RUN apt-get update && apt-get install -y wget tar jq vim
RUN cd /tmp && wget https://nodejs.org/dist/v8.4.0/node-v8.4.0-linux-x64.tar.xz
RUN mkdir -p /usr/local && cd /usr/local && tar -xf /tmp/node-v8.4.0-linux-x64.tar.xz && \
    ln -s /usr/local/node-v8.4.0-linux-x64/bin/node /usr/local/bin && \
    ln -s /usr/local/node-v8.4.0-linux-x64/bin/npm /usr/local/bin

RUN mkdir -p /usr/local/mlst /opt/mlst/databases && chmod -R a+w /opt/mlst/databases
COPY index.js update-mlst-databases.js package.json /usr/local/mlst/
COPY src /usr/local/mlst/src/

RUN cd /usr/local/mlst && \
    /usr/local/bin/npm install && \
    DEBUG='*,-follow-redirects,-trace*' /usr/local/bin/node --max-old-space-size=4096 ./update-mlst-databases.js && \
    chmod -R a+r /opt/mlst/databases # Built 20 October 2017

USER biodocker

CMD [ "/usr/local/bin/node", "--max-old-space-size=4096", "/usr/local/mlst/index.js" ]
