ARG     DATA_VERSION
ARG     DATA_NAME

FROM    ubuntu:22.04 as blast_build

RUN     apt-get update && apt-get install -y wget tar && \
        wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-x64-linux.tar.gz && \
        tar xzvf ncbi-blast-*-x64-linux.tar.gz && \
        mv ncbi-blast-*/bin /blast

FROM    registry.gitlab.com/cgps/cgps-mlst/${DATA_NAME}-data:${DATA_VERSION} as data

FROM    node:16-slim as base_build

RUN     apt-get update && apt-get install -y git python3

COPY    --from=blast_build /blast/blastn /blast/makeblastdb /usr/local/bin/
COPY    --from=data /usr/local/mlst/index_dir /usr/local/mlst/index_dir

RUN     cd /usr/local/mlst/ && \
        chmod -R a+rw index_dir

WORKDIR /usr/local/mlst

CMD     /bin/bash
