ARG     DB_TAG
ARG     CODE_VERSION

FROM    registry.gitlab.com/cgps/pathogenwatch/analyses/typing-databases:${DB_TAG} as schemes

FROM    registry.gitlab.com/cgps/cgps-mlst/mlst-code:${CODE_VERSION} as index_build

WORKDIR /usr/local/mlst

COPY    --from=schemes /db/schemes.json /typing-databases/schemes.json
COPY    --from=schemes /db/cgmlst_schemes /typing-databases/cgmlst_schemes
COPY    --from=schemes /db/mlst_schemes /typing-databases/mlst_schemes
COPY    --from=schemes /db/other_schemes /typing-databases/other_schemes

ARG SCHEME
ARG TYPE

ENV SCHEME=${SCHEME:-IGNORE}
ENV TYPE=${TYPE:-IGNORE}

RUN npm run index  -- --scheme=${SCHEME} --type=${TYPE} --index=index_dir --database=/typing-databases

ENTRYPOINT /bin/bash


